[package]
name = "Ankara"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.13"
thiserror="1.0"
clap = "2.33"
rand = "0.8.0"